### ISSUE TITLE
Add "should be present" and "should not be present" to Then steps

### ISSUE THREAD

**Issue by Marketionist** [revjet-qa/wdio-cucumber-steps#37]
Add "should be present" and "should not be present" to `Then` steps (https://github.com/revjet-qa/wdio-cucumber-steps/blob/master/src/steps/then.js)

**Comment by Lisalexandr** [comment]
It's already done

**Comment by Marketionist** [comment]
Fixed in https://github.com/revjet-qa/wdio-cucumber-steps/pull/21
